# called before build
import subprocess

# Get 0.0.0 version from latest Git tag
tagcmd = "git describe --tags --abbrev=0"
try:
	version = subprocess.check_output(tagcmd, shell=True).decode().strip()
except Exception:
	version = "1.0"
revcmd = "git log --pretty=format:%h -n 1"
try:
	commit = subprocess.check_output(revcmd, shell=True).decode().strip()
except Exception:
	commit = "deadbeef"

f = open("include/version.h", "w")
f.write('#ifndef _VERSION_H\n')
f.write('#define _VERSION_H\n')
f.write('// automatically generated by pre_script.py\n')
f.write('#define VERS_TAG "{}-{}"\n'.format(version, commit))
f.write('#endif /* _VERSION_H */\n')
f.close()